docs/javascript-api.md

I used this ruby script to generate it: http://stackoverflow.com/a/22131019/640584

Add table of contents to javascript api page

---

_includes/docs_contents.html
docs/android.md
docs/frida-cli.md
docs/frida-discover.md
docs/frida-ps.md
docs/frida-trace.md

Lots to be written still, and have to figure out a few examples

CLI utilities docs

---

docs/ios.md

Update docs for iOS usbmuxd on linux support

---

_config.yml
_includes/top.html
docs/index.md
docs/installation.md
docs/troubleshooting.md

Added a constant for organization url in config and fixed links

[file an issue] link won't work

---

docs/installation.md

Added a note for example won't work on El Capitan
Related to frida/frida#83

Add a note for El Capitan

---

docs/quickstart.md

Corrected the App name to match with the example.

Fixed a typo

---

_docs/quickstart.md

Fix small mistakes in Twitter example on quickstart page

---

_docs/installation.md

Note about issue with OS X El Capino in more visible place

---

_docs/examples/ios.md

Moved the example of alert box on iOS 7 From Javascript-API section and adding alert box for iOS 8

Update for iOS examples

---

_data/docs.yml
_docs/c-api.md
_docs/swift-api.md

Allows people to realize they can use C & Swift and shows them
where to get the devkits to get started.

Add very basic docs for Swift & C

---

_docs/examples/windows.md

This javascript syntax works for me on windows, the old gave a script parse error.

Update windows.md javascript syntax

---

_docs/javascript-api.md

Added an example for Interceptor context properties. 
Modified after review.

Added an example for Interceptor context properties 

---

_docs/examples/android.md

Added an example of instantiating Java/Android classes including the use of overloads, as well as hooking/interceping methods.

Added an extra Java/Android example.

---

_docs/examples/linux.md

Add some information about running Friday using Linux as a Docker container.

Add linux+docker info for frida

---

_docs/javascript-api.md

related to https://github.com/frida/frida-objc/pull/16#issuecomment-503787037

docs($moduleName): Add new special property

---

_docs/troubleshooting.md

As shown [here](https://github.com/frida/frida/issues/824) Magisk Hide could interfere with ptrace

Reference to Magisk Hide issues

---

_docs/gadget.md

Took me a while to figure this out.
Many thanks to Romain Thomas for writing the article referenced in the changes!

Add gadget config notes for Android

---

_i18n/en/_docs/presentations.md

Original site is dead, long live archive.org

Updated OSDC links to point archive.org

---

contact/index.html

Telegram channels are for broadcasting: https://telegram.org/tour/channels
Telegram groups are chats: https://telegram.org/tour/groups

Change "Telegram channel" to "Telegram group" in contact page

---

_i18n/en/_docs/frida-trace.md

Missing backslash on frida-trace page

---

_i18n/en/_docs/javascript-api.md

Noticed this while I was running your sample code.

Missed an open parenthesis

---

_i18n/en/_docs/functions.md

Made me double take when I first read the docs. Cheers!

Fix modify function example to maintain its true time

---

_i18n/en/_docs/javascript-api.md

I believe this should be added in the documentation.

document Thread.backtrace limitation

---

_data/docs.yml
_docs/gum-graft.md
_i18n/en/_docs/gum-graft.md

A short documentation for gum-graft.

Gum graft docs

---

_i18n/en/_docs/footprint.md

Include when each feature is relevant and when it may disabled

Expand footprint.md

---

_i18n/en/_docs/quickstart.md

correct branch name on quickstart.md

fix tracer url
