docs/javascript-api.md
highlight block breaks indention of the following text, so md interprets that text as code block. fixed making list item
=> fix broken markdown formatting

docs/javascript-api.md
Add `Memory.readFloat`, `Memory.readDouble`, `Memory.writeFloat` and `Memory.writeDouble` to the JavaScript API documentation.
=> Add `Memory.readFloat`, `Memory.readDouble`, `Memory.writeFloat` and `Memory.writeDouble`

docs/javascript-api.md
Removed "alive" text that caused slight confusion as to which threads were enumerated
=> Tweak to enumerateThreads documentation

_docs/javascript-api.md
Moved example of alert box on iOS 7 to iOS Examples and added some explanation on passing messages to ObjC class instances in Frida.
=> Update Javascript-API for iOS

_docs/javascript-api.md
added in 2a90aec3fc826d3be6df6e3e0a56d0874d504840. This method is useful for calling methods that must be executed from the main thread, e.g. WebView.setWebContentsDebuggingEnabled()
=> document the Java.scheduleOnMainThread() method

_docs/examples/ios.md, _docs/javascript-api.md
I've added some information in two different places. More specifically, this is some documentation for the ObjC.Object function in combination with the interceptor.
One iOS example was added with a little bit of information. A shorter version of the example replaces the current example for ObjC.Object to also provide a little bit of extra information for that specific usage.
=> Updated ObjC documentation

_docs/javascript-api.md
This is described correctly in the text, but the example is incorrect...
=> rpc example: items in export should be key:value pairs

_docs/javascript-api.md
Mostly to tell people how to monitor for when a process exits.
It could also mention signals that seem to exist for things like PyDeviceManager, but I haven't tried those to confirm.
=> Add information about signals

_docs/c-api.md
Change the table into a set of headers with comments.
Primarily because the CSS for Markdown tables is broken, so the text was grey on grey.
It also makes it more similar to the other pages.
=> Remove the table from the C docs

_docs/building.md
Page was kind of long, so I added a TOC at the top like other pages have.
Added a link to the hacking page, which is kind of void currently, but
`make` is incorrect to tell people, as it will just provide a vague help.
=> Add TOC and link to hacking page

_docs/javascript-api.md
- Made it clear that this is a special case and not needed for common C++ class/Frida interop.
- Reduced the Frida API use in the example to make it easier to understand.
=> Clarify scenario and example for newcomers

_docs/building.md
I replaced lib32stdc++-4.9-dev by lib32stdc++-4.8-dev 
as 4.9 doesn't seem to be available on Ubuntu 14.04
http://packages.ubuntu.com/trusty/libstdc++-4.8-dev
=> Add more details to build on Ubuntu 14.04

_docs/examples/ios.md
There were a few things that were somewhat confusing to me when looking at this, so I tried to clarify them here:
- Add a big tip at the top showing how to examine the actual class type that was decoded using `ObjC.Object()`
- Expanded some examples to have more copy/paste-able code since `data`, `array`, and `dict` are all created the same way, which wasn't 100% obvious to me 
- I also added the `valueOf()` call to the array example which we discussed
- ~~I also fixed a bug in the loop logic, as iterating the length of the array ends up blowing things up for me (and seems to be a off-by-one issue).~~ - this was caused by the missing `valueOf()` call!
Thanks again for your help tonight!
=> Add in a few updates to the IOS/Obj-c docs

_docs/examples/android.md
There is no document to explain how to set field's value when the field name is the same as a method name. This patch adds this.
=> Add explain for setting field's value

_docs/installation.md, _docs/quickstart.md, index.html
Executing `pip install` with administrator privileges can be harmful and is considered insecure.
Not meaning that frida is harmful, of course, but that `sudo` may discourage new users from installing and trying frida.
Besides, in the instructions in Frida's [main repo](https://github.com/frida/frida), `pip install` is executed without sudo.
=> Execute pip without sudo

_docs/android.md
The Android documentation could use an enhancement for instructions on decompressing XZ files. It took me a few minutes to find that it needed to be decompressed as well as the correct utility. Other users have run into this in the past too.
https://github.com/frida/frida/issues/364
https://github.com/frida/frida/issues/367
It's a bit more verbose but can help beginners like myself.
=> Improve Android documentation

_docs/frida-trace.md
This is a first stab at documenting the frida-trace tool's command line
options.  In this PR there are only seven (7) options that are described
in depth.
It is hoped that the other command line options will eventually all be
documented.
=> Add frida-trace documentation

_i18n/en/_docs/javascript-api.md
Based on experience using the library and reading the gum code, it looks like Module.load() expects a file system path. The documentation implies that it expects the name of the module.
=> clarify what Module.load() expects

_docs/examples/ios.md
- Changed all the initial examples to focus on iOS and USB devices only.
- Added how to list running apps.
- Remove $ sign at the end in native tracing:  It's not required... in fact, it returns 0 functions traced instead.
- Remove non-USB related examples for iOS.
- Other minor formatting changes...
=> Several updates to the Frida iOS documentation

_i18n/en/_docs/building.md
Just to make things a little clearer about the steps required for successful builds under Windows.
- Python38 has to be in a specific directory otherwise `frida-python` will not find the necessary includes
- make it marginally clearer about the setup  of visual studio and setting up of python
=> Add more detailed build instructions for Windows 

_i18n/en/_docs/javascript-api.md
Syntax-highlighted blocks of code are not supported in lists so the example must be removed.
=> Remove page-breaking example

_i18n/en/_docs/android.md
Added some clarity about using `adb root` on a device that might get this error:
`adbd cannot run as root in production builds`
=> Added info about android roduction builds when using adb root

_i18n/en/_posts/2021-06-16-frida-15-0-released.markdown
The news was from July not from June
=> Fix wrong date in documentation

_docs/examples/windows.md, _i18n/en/_docs/examples/windows.md, _i18n/en/_docs/functions.md, _i18n/en/_docs/installation.md, _i18n/en/_docs/messages.md, _i18n/en/_posts/2016-06-02-frida-7-2-released.markdown, _i18n/en/_posts/2018-04-28-frida-10-8-released.markdown
According to the above example.py, this doc uses Python3. As a result, it's weird for string with u prefix.
=> Remove redundant u prefix

_i18n/en/_docs/examples/ios.md
Looks like you changed to a jinja-style template, but not all the blocks have been changed. This PR fixes the blocks.
=> Fix code blocks in iOS examples page

_i18n/en/_docs/installation.md
Before:
```
me-mbp ~/w/frida$ python3 hello.py
/Users/me/w/frida/hello.py:16: DeprecationWarning: Script.exports will become asynchronous in the future, use the explicit Script.exports_sync instead
print([m["name"] for m in script.exports.enumerate_modules()])
['yello', 'libSystem.B.dylib', 'libcache.dylib', 'libcommonCrypto.dylib', 'libcompiler_rt.dylib', 'libcopyfile.dylib', 'libcorecrypto.dylib', 'libdispatch.dylib', 'libdyld.dylib', 'libkeymgr.dylib', 'libmacho.dylib', 'libquarantine.dylib', 'libremovefile.dylib', 'libsystem_asl.dylib', 'libsystem_blocks.dylib', 'libsystem_c.dylib', 'libsystem_collections.dylib', 'libsystem_configuration.dylib', 'libsystem_containermanager.dylib', 'libsystem_coreservices.dylib', 'libsystem_darwin.dylib', 'libsystem_darwindirectory.dylib', …
```
=> Address deprecation warning in sample script

_i18n/en/_docs/javascript-api.md
What used to be a oneliner now needs to retrieve a reference to the module first.
Code examples in the docs were still using the old style.
=> docs: frida 17 change to getExportByName()
